### ISSUE TITLE
Optimisation of playlist playback

### ISSUE THREAD

**Issue by flkrz** [lucaspape/catplayer#21]
**Is your feature request related to a problem? Please describe.**
Playlist playback from #19 works great, especially with the added shuffle and loop controls. Nice work! 

From a performance and UX perspective, the way the app has to write a queue of each track on the playlist may confuse people as they'll just see tracks cycling through really quick without playing. Obviously it starts playing once the playlist is loaded, but this behaviour would be very frustrating on a large playlist (I'll test a 55 track playlist when I get the chance). 

**Describe the solution you'd like**
I don't know exactly how tracks are identified for the playback queue, but either using a string array to store track IDs and optimising the population of this to pull only metadata? Is that what you already do? Is that even possible or a viable efficiency improvement?

Otherwise, can the app cheat a bit, pick the first song from the playlist, set that as track one, start playing it, then run a background thread to queue everything else? Just a couple of random ideas that spring to mind. 

**Describe alternatives you've considered**
A different approach is to automatically download playlist data and generate a playlist entry that gets stored on the phone. Not necessarily a full track download, but the information required to make the playlist ready to go? Not sure what the scope and impacts of this could be though.

**Comment by lucaspape** [comment]
I am not sure what exactly you mean by "they'll see tracks cycling through really quick without playing". When can you see something like this, because I don't think this is intentional. 

To your proposed alternative:
It should already save every song into a database on the phone. It saves everything needed for playback except the playback file.
It should only get the data from the internet if there isn't any already saved or if you refresh.

The track-queue is an array of song objects which have to be created before added to the playlist. I will probably change this to simple strings and load the extra stuff it is played, that should work faster. Currently it should create the first song object and then run a background thread for the rest like you described (but I am not sure if I did it like this in playlists too).

**Comment by flkrz** [comment]
Sorry, forgot to share the screen capture.

http://severas.rm-ni.uk:8080/C.A.S./req0016-20200105/mobizen_20200105_234837.mp4

**Comment by lucaspape** [comment]
Oh wow, well this is not normal. I will look into that again

**Comment by lucaspape** [comment]
It seems like this is a weird side effect of playing next without already playing a song. If you play a song and then "play next" this does not happen.

**Comment by lucaspape** [comment]
The same thing happened with playing albums next without playing a track first. I fixed it now.

**Comment by flkrz** [comment]
Confirmed, 0.0.8.3 works great, nice and fast.
